DROP TABLE IF EXISTS account;

CREATE TABLE account (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    customer_id SMALLINT UNSIGNED NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance DECIMAL(10,2) NOT NULL
)